---
- name: Install JDK
  yum:
    name: " java-1.{{ java_version }}.0-openjdk-devel"
    state: "{{ 'present' if java_devel == 1 else 'absent' }}"

- name: Install JRE
  yum:
    name: " java-1.{{ java_version }}.0-openjdk"
