---
- name: Install JDK
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: "{{ 'present' if java_devel == true else 'absent' }}"

- name: Install JRE
  apt:
    name: "openjdk-{{ java_version }}-jre"

